### ISSUE TITLE
Cannot read property "filter" of undefined

### ISSUE THREAD

**Issue by msageryd** [fabiospampinato/vscode-projects-plus-todo-plus#1] opened 2017-11-29 08:56 UTC
I'm using Project+ and Todo+. Thought I'd try out "Project+ Todo+" for an overview. 

When I select the command "Projects: Todo" i get `Cannot read property "filter" of undefined`

**Comment by fabiospampinato** [comment] 2017-11-30 10:15
Thanks for reporting the problem, I'll investigate this as soon as I get some free time.

**Comment by fabiospampinato** [comment] 2017-12-18 17:06
@msageryd I can't reproduce the problem, can you try using v1.4.0 and see if that fixes it?

**Comment by fabiospampinato** [comment] 2018-07-04 23:01
No needed info provided, I'm closing this.

**Closed as completed by fabiospampinato** 2018-07-04 23:01 UTC
Labels: needs more info
